# Dhia Salsabila Azhar

# (18/430187/PA/18700) 

---






Melihat kemiripan teks antara docA, docB, dan docC


In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
docA = "Automatic Facial Expression Recognition FER is an active research area in artificial intelligence and image processing One of the main challenges in FER is the automatic feature extraction In this paper the proposed 10 layer Convolutional Neural Network CNN architecture can automatically detect important features without human supervision This research uses Extended CohnKanade CK+ dataset and Japanese Female Facial Expression JAFFE dataset for facial expression recognition The proposed architecture achieved an accuracy of 99.3% and 78.1% in classifying facial expressions in CK+ and JAFFE datasets"
docB = "Aiming at the problem of inaccurate location caused by missing information after feature extraction in traditional multitask cascade convolution network feature pyramid structure is used to strengthen the context connection of images aiming at the inaccuracy of face detection caused by difficult samples an new combined loss function is applied and an improved multitask convolution network is proposed based on softNMS Non maximum suppression The network shows excellent performance on public data sets selfmade data sets and has higher accuracy than traditional MTCNN Multitask convolutional neural network"
docC = "Surveillance systems in spite of the recent advances still poses many challenges especially in the field of patrolling or tracking of subjects through CCTV footage or any other portable drone mechanisms Real time monitoring of public places for possible suspects are still made through manual observations in many places The manual labour involved and the human errors that can occur makes the system less efficient Many research attempts were made for designing foolproof systems and still going on understanding the importance of the problem This paper presents the implementation of an intelligent multicamera Face Recognition based surveillance system using FaceNet and MTCNN algorithm on Jetson TX2 The proposed portable system tracks the subject or the suspect with the camera ID or location together with the timestamp and logs his presence in the database using multiple camera installation"

Mengekstrak kata yang ada di dalam setiap dokumen

In [ ]:
bagOfWordsA = docA.split(' ')
bagOfWordsB = docB.split(' ')
bagOfWordsC = docC.split(' ')

print(bagOfWordsA)
print(bagOfWordsB)
print(bagOfWordsC)

['Automatic', 'Facial', 'Expression', 'Recognition', 'FER', 'is', 'an', 'active', 'research', 'area', 'in', 'artificial', 'intelligence', 'and', 'image', 'processing', 'One', 'of', 'the', 'main', 'challenges', 'in', 'FER', 'is', 'the', 'automatic', 'feature', 'extraction', 'In', 'this', 'paper', 'the', 'proposed', '10', 'layer', 'Convolutional', 'Neural', 'Network', 'CNN', 'architecture', 'can', 'automatically', 'detect', 'important', 'features', 'without', 'human', 'supervision', 'This', 'research', 'uses', 'Extended', 'CohnKanade', 'CK+', 'dataset', 'and', 'Japanese', 'Female', 'Facial', 'Expression', 'JAFFE', 'dataset', 'for', 'facial', 'expression', 'recognition', 'The', 'proposed', 'architecture', 'achieved', 'an', 'accuracy', 'of', '99.3%', 'and', '78.1%', 'in', 'classifying', 'facial', 'expressions', 'in', 'CK+', 'and', 'JAFFE', 'datasets']
['Aiming', 'at', 'the', 'problem', 'of', 'inaccurate', 'location', 'caused', 'by', 'missing', 'information', 'after', 'feature', 'extraction

Mencari kata unik dalam dokumen A,B, dan C

In [ ]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB)).union(set(bagOfWordsC))
print(uniqueWords)

{'Female', 'possible', 'used', 'combined', 'recent', 'going', 'ID', 'human', 'recognition', 'drone', 'footage', 'algorithm', 'Facial', 'the', 'than', 'involved', 'understanding', 'at', 'classifying', 'This', 'has', 'excellent', 'Multitask', 'field', 'places', 'inaccurate', 'errors', 'importance', 'new', 'achieved', 'of', 'monitoring', 'observations', 'occur', 'samples', 'context', 'location', 'facial', 'JAFFE', 'cascade', 'TX2', 'detect', 'tracks', 'Expression', 'intelligent', 'portable', 'Recognition', 'Japanese', 'an', 'convolutional', 'important', 'convolution', 'performance', 'other', 'camera', 'improved', 'Automatic', 'manual', 'tracking', 'labour', 'presence', 'Extended', 'designing', '99.3%', 'after', 'timestamp', 'his', 'time', 'pyramid', 'suppression', 'automatic', 'efficient', 'subject', 'FER', 'or', 'Face', 'extraction', 'is', 'database', 'suspect', 'still', 'logs', 'many', 'main', 'One', 'inaccuracy', 'information', 'suspects', 'less', 'features', 'detection', 'spite', 'are

In [ ]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1

numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1

numOfWordsC = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsC:
    numOfWordsC[word] += 1

In [ ]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

Menghitung seberapa sering kemunculan kata pada ketiga dokumen

In [ ]:
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)
tfC = computeTF(numOfWordsC, bagOfWordsC)
print(tfA)
print(tfB)
print(tfC)

{'Female': 0.011764705882352941, 'possible': 0.0, 'used': 0.0, 'combined': 0.0, 'recent': 0.0, 'going': 0.0, 'ID': 0.0, 'human': 0.011764705882352941, 'recognition': 0.011764705882352941, 'drone': 0.0, 'footage': 0.0, 'algorithm': 0.0, 'Facial': 0.023529411764705882, 'the': 0.03529411764705882, 'than': 0.0, 'involved': 0.0, 'understanding': 0.0, 'at': 0.0, 'classifying': 0.011764705882352941, 'This': 0.011764705882352941, 'has': 0.0, 'excellent': 0.0, 'Multitask': 0.0, 'field': 0.0, 'places': 0.0, 'inaccurate': 0.0, 'errors': 0.0, 'importance': 0.0, 'new': 0.0, 'achieved': 0.011764705882352941, 'of': 0.023529411764705882, 'monitoring': 0.0, 'observations': 0.0, 'occur': 0.0, 'samples': 0.0, 'context': 0.0, 'location': 0.0, 'facial': 0.023529411764705882, 'JAFFE': 0.023529411764705882, 'cascade': 0.0, 'TX2': 0.0, 'detect': 0.011764705882352941, 'tracks': 0.0, 'Expression': 0.023529411764705882, 'intelligent': 0.0, 'portable': 0.0, 'Recognition': 0.011764705882352941, 'Japanese': 0.01176

In [ ]:
def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [ ]:
idfs = computeIDF([numOfWordsA, numOfWordsB, numOfWordsC])
print(idfs)

{'Female': 1.0986122886681098, 'possible': 1.0986122886681098, 'used': 1.0986122886681098, 'combined': 1.0986122886681098, 'recent': 1.0986122886681098, 'going': 1.0986122886681098, 'ID': 1.0986122886681098, 'human': 0.4054651081081644, 'recognition': 1.0986122886681098, 'drone': 1.0986122886681098, 'footage': 1.0986122886681098, 'algorithm': 1.0986122886681098, 'Facial': 1.0986122886681098, 'the': 0.0, 'than': 1.0986122886681098, 'involved': 1.0986122886681098, 'understanding': 1.0986122886681098, 'at': 1.0986122886681098, 'classifying': 1.0986122886681098, 'This': 0.4054651081081644, 'has': 1.0986122886681098, 'excellent': 1.0986122886681098, 'Multitask': 1.0986122886681098, 'field': 1.0986122886681098, 'places': 1.0986122886681098, 'inaccurate': 1.0986122886681098, 'errors': 1.0986122886681098, 'importance': 1.0986122886681098, 'new': 1.0986122886681098, 'achieved': 1.0986122886681098, 'of': 0.0, 'monitoring': 1.0986122886681098, 'observations': 1.0986122886681098, 'occur': 1.098612

In [ ]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [ ]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
tfidfC = computeTFIDF(tfC, idfs)
df = pd.DataFrame([tfidfA, tfidfB, tfidfC])
print(df)

     Female  possible      used  combined  ...  and   systems     image  CohnKanade
0  0.012925  0.000000  0.000000  0.000000  ...  0.0  0.000000  0.012925    0.012925
1  0.000000  0.000000  0.012628  0.012628  ...  0.0  0.000000  0.000000    0.000000
2  0.000000  0.008019  0.000000  0.000000  ...  0.0  0.016038  0.000000    0.000000

[3 rows x 193 columns]


In [ ]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([docA, docB, docC])
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)
print(df)

         10        78        99  ...      were      with   without
0  0.092574  0.092574  0.092574  ...  0.000000  0.000000  0.092574
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.000000  ...  0.063896  0.127792  0.000000

[3 rows x 178 columns]


# Mengukur dengan cosine coefficient

---



In [ ]:
doc12 = [docA,docB]
doc13 = [docB,docC]
doc23 = [docA, docC]

In [ ]:
import nltk, string, numpy
nltk.download('punkt') # first-time use only
stemmer = nltk.stem.porter.PorterStemmer()
def StemTokens(tokens):
    return [stemmer.stem(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def StemNormalize(text):
    return StemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
nltk.download('wordnet') # first-time use only
lemmer = nltk.stem.WordNetLemmatizer()

def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfTran = TfidfTransformer(norm="l2")

In [ ]:
import math

def idf(n,df):
    result = math.log((n+1.0)/(df+1.0)) + 1
    return result

In [ ]:
LemVectorizer = CountVectorizer(tokenizer=LemNormalize, stop_words='english')
LemVectorizer.fit_transform(doc12)
print (LemVectorizer.vocabulary_)

{'automatic': 11, 'facial': 37, 'expression': 33, 'recognition': 73, 'fer': 40, 'active': 5, 'research': 74, 'area': 9, 'artificial': 10, 'intelligence': 51, 'image': 45, 'processing': 69, 'main': 57, 'challenge': 16, 'feature': 38, 'extraction': 35, 'paper': 66, 'proposed': 70, '10': 0, 'layer': 54, 'convolutional': 25, 'neural': 63, 'network': 62, 'cnn': 19, 'architecture': 8, 'automatically': 12, 'detect': 29, 'important': 46, 'human': 44, 'supervision': 81, 'extended': 34, 'cohnkanade': 20, 'ck': 17, 'dataset': 27, 'japanese': 53, 'female': 39, 'jaffe': 52, 'achieved': 4, 'accuracy': 3, '993': 2, '781': 1, 'classifying': 18, 'datasets': 28, 'aiming': 6, 'problem': 68, 'inaccurate': 49, 'location': 55, 'caused': 15, 'missing': 59, 'information': 50, 'traditional': 83, 'multitask': 61, 'cascade': 14, 'convolution': 24, 'pyramid': 72, 'structure': 80, 'used': 84, 'strengthen': 79, 'context': 23, 'connection': 22, 'inaccuracy': 48, 'face': 36, 'detection': 30, 'difficult': 31, 'sample'

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [ ]:
tf_matrix = LemVectorizer.transform(doc12).toarray()
print(tf_matrix)

[[1 1 1 1 1 1 0 0 2 1 1 2 1 0 0 0 1 2 1 1 1 0 0 0 0 1 0 2 1 1 0 0 0 4 1 1
  0 4 2 1 2 0 0 0 1 1 1 0 0 0 0 1 2 1 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 2 0
  0 2 2 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 2 1 0 0 0 0 0 1 1 2 0 0 0 0 0 1 1 1 2 1 2 0 0 0 1 1 1 0 0 1
  1 0 2 0 0 1 1 1 0 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 3 4 1 1 1 0 1 1 0 1 1
  1 0 0 1 1 2 1 1 1 0 1 2 1]]


In [ ]:
tf_matrix.shape

(2, 85)

In [ ]:
tfidfTran.fit(tf_matrix)

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

In [ ]:
print("The idf for terms that appear in one document: " , str(idf(2,1)))
print("The idf for terms that appear in two documents: " , str(idf(2,2)))

The idf for terms that appear in one document:  1.4054651081081644
The idf for terms that appear in two documents:  1.0


In [ ]:
tfidf_matrix = tfidfTran.transform(tf_matrix)

In [ ]:
cos_similarity_matrix = (tfidf_matrix * tfidf_matrix.T).toarray()
print(cos_similarity_matrix)

[[1.         0.08598854]
 [0.08598854 1.        ]]


Dengan Scikit Learn

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')

def cos_similarity(textlist):
    tfidf = TfidfVec.fit_transform(textlist)
    return (tfidf * tfidf.T).toarray()

In [ ]:
cos_similarity(doc12)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


array([[1.        , 0.08598854],
       [0.08598854, 1.        ]])

In [ ]:
cos_similarity(doc13)

array([[1.        , 0.04003234],
       [0.04003234, 1.        ]])

In [ ]:
cos_similarity(doc23)

array([[1.        , 0.04994991],
       [0.04994991, 1.        ]])