Nama : Dhia Salsabila Azhar

NIM : 18/430187/PA/18700

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Mengklasifikasikan Iris dataset menggunakan algoritma Neural Network 

<img src="https://www.pyimagesearch.com/wp-content/uploads/2019/01/python_ml_iris.jpg"></img>

Terdapat 4 fitur berupa panjang sepal, lebar sepal, panjang tepal dan lebar tepal (dalam CM)
digunakan untuk mengklasifikasikan bunga menjadi 3 kelas yaitu 

1.Iris Setosa
2.Iris Versicolor
3.Iris Virginica


<img src="https://docs.google.com/uc?export=download&id=1vlpLHw58XdERtGusg-tOlwS-vJQi_9nz"></img>
MENGIMPORT LIBRARY

In [ ]:
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import SGD
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.datasets import load_iris

<img src="https://docs.google.com/uc?export=download&id=1X1FEn2_NViLv9OQIInWvfv32psVF9eHn"></img>
Meload dataset iris dan membagi 75%training dan 25% testing

In [ ]:
print("[INFO] loading data...")
dataset = load_iris()
(trainX, testX, trainY, testY) = train_test_split(dataset.data, dataset.target, test_size=0.25)

[INFO] loading data...


Meng encode Label menjadi 1- hot vector(vektor binary yg true cuman salah satu) ex : [1 0 0] , sebagai penanda label 
<img src="https://docs.google.com/uc?export=download&id=1qEJH_k18WABTEr4lVDukk6Ir3yh-HsoV"></img>

In [ ]:
lb = LabelBinarizer()
trainY = lb.fit_transform(trainY)
testY = lb.transform(testY)
print(testY)

[[0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]]


Membuat model NN 4 input => 3 hidden layer (fungsi sigmoid) => 3 hidden layer (fungsi sigmoid) => 3 output (fungsi softmax) 4input karena 4 ciri berupa panjang dan lebar , 3 output karena 3 klas bunga
<img src="https://docs.google.com/uc?export=download&id=1QWc-EwUP-6o6KBpNcUQU3eyj7MalWrUy"></img>

In [ ]:
model = Sequential()
model.add(Dense(3, input_shape=(4,), activation="sigmoid"))
model.add(Dense(3, activation="sigmoid"))
model.add(Dense(3, activation="softmax"))

Melatih menggunakan optimasi minimalkan error SGD dengan iterasi 250. Lalu dilakukan testing di dataset  25% yg telah dibagi di awal 
<img src="https://docs.google.com/uc?export=download&id=1HAr5fKZYWsjQ2TbMoTLBGv1t8wTz8ojn"></img>

In [ ]:
print("[INFO] training network...")
opt = SGD(lr=0.1, momentum=0.9, decay=0.1/250)
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
H = model.fit(trainX, trainY, validation_data=(testX, testY), epochs=250, batch_size=16)

print("[INFO] evaluating network...")
predictions = model.predict(testX, batch_size=16)
print(classification_report(testY.argmax(axis=1), predictions.argmax(axis=1), target_names=dataset.target_names))

[INFO] training network...
Epoch 1/250
7/7 [==============================] - 0s 20ms/step - loss: 1.1316 - accuracy: 0.3304 - val_loss: 1.1159 - val_accuracy: 0.2895
Epoch 2/250
7/7 [==============================] - 0s 4ms/step - loss: 1.1102 - accuracy: 0.3482 - val_loss: 1.1172 - val_accuracy: 0.2632
Epoch 3/250
7/7 [==============================] - 0s 4ms/step - loss: 1.1119 - accuracy: 0.3571 - val_loss: 1.1261 - val_accuracy: 0.2632
Epoch 4/250
7/7 [==============================] - 0s 3ms/step - loss: 1.1166 - accuracy: 0.2768 - val_loss: 1.1390 - val_accuracy: 0.2895
Epoch 5/250
7/7 [==============================] - 0s 4ms/step - loss: 1.1194 - accuracy: 0.3571 - val_loss: 1.1123 - val_accuracy: 0.2632
Epoch 6/250
7/7 [==============================] - 0s 4ms/step - loss: 1.0822 - accuracy: 0.3661 - val_loss: 1.1158 - val_accuracy: 0.2895
Epoch 7/250
7/7 [==============================] - 0s 4ms/step - loss: 1.0519 - accuracy: 0.5268 - val_loss: 1.0825 - val_accuracy: 0.4211

## Mengklasifikasikan DATA foto 3scenes dataset 

<img src="https://www.pyimagesearch.com/wp-content/uploads/2019/01/python_ml_3scenes.jpg"></img>

scenes dataset and includes 948 total images of 3 scenes:

Coast (360 of images)
Forest (328 of images)
Highway (260 of images)


<img src="https://docs.google.com/uc?export=download&id=1zcywBJszoktqJ72b0Ok50tv1gCQIEOZa"></img>

First, we import our necessary packages on Lines 2-16. It looks like a lot, but you’ll recognize most of them from the previous script. The additional imports for this script include:

The LabelEncoder  will be used to transform textual labels into numbers (Line 9).
A basic image processing tool called PIL/Pillow (Line 12).
My handy module, paths , for easily grabbing image paths from disk (Line 13). This is included in my personal imutils package which I’ve released to GitHub and PyPi.
NumPy will be used for numerical computations (Line 14).
Python’s built-in os  module (Line 16). We’ll use it for accommodating path separators among different operating systems.

In [ ]:
# import the necessary packages
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from PIL import Image
from imutils import paths
import numpy as np
import argparse
import os


<img src="https://docs.google.com/uc?export=download&id=1kgRnS_VcABzJp508pU839PH-Hsg3ibCE"></img>

Karena Machine learning memiliki performa yg buruk pada pengolahan pixel gambar secara langsuung maka diperlukan extraksi ciri terlebih dulu.

Ciri yang diekstrak adalah rata2 dan standar deviasi. Setiap gambar dipisah dahulu channel R , G , B sehingga 1 gambar akan memilikin 3 x 2 = 6 fitur.

Pengolahan datanya menggunakan Numpy

In [ ]:
def extract_color_stats(image):
	# split the input image into its respective RGB color channels
	# and then create a feature vector with 6 values: the mean and
	# standard deviation for each of the 3 channels, respectively
	(R, G, B) = image.split()
	features = [np.mean(R), np.mean(G), np.mean(B), np.std(R),
		np.std(G), np.std(B)]

	# return our set of features
	return features


<img src="https://docs.google.com/uc?export=download&id=1eAzKFXkesWI3PV_92KlLPOW6FL80NiDi"></img>

In [ ]:
args = "knn"

# define the dictionary of models our script can use, where the key
# to the dictionary is the name of the model (supplied via command
# line argument) and the value is the model itself
models = {
	"knn": KNeighborsClassifier(n_neighbors=1),
	"naive_bayes": GaussianNB(),
	"logit": LogisticRegression(solver="lbfgs", multi_class="auto"),
	"svm": SVC(kernel="linear"),
	"decision_tree": DecisionTreeClassifier(),
	"random_forest": RandomForestClassifier(n_estimators=100),
	"mlp": MLPClassifier()
}

print("[INFO] extracting image features...")
imagePaths = paths.list_images("/content/python-machine-learning/3scenes")
#imagePaths = paths.list_images(args["dataset"])
data = []
labels = []

[INFO] extracting image features...



<img src="https://docs.google.com/uc?export=download&id=1RpL84obFnYyUgHVjlWgL2GkWRsSmY43l"></img>

In [ ]:
for imagePath in imagePaths:
	# load the input image from disk, compute color channel
	# statistics, and then update our data list
	image = Image.open(imagePath)
	features = extract_color_stats(image)
	data.append(features)

	# extract the class label from the file path and update the="path to directory containing the '3scenes' dataset")
#args = vars(ap.parse_args())
	# labels list
	label = imagePath.split(os.path.sep)[-2]
	labels.append(label)

# encode the labels, converting them from strings to integers
le = LabelEncoder()
labels = le.fit_transform(labels)

# perform a training and testing split, using 75% of the data for
# training and 25% for evaluation
(trainX, testX, trainY, testY) = train_test_split(data, labels, test_size=0.25)
#(trainX, testX, trainY, testY) = train_test_split(dataset.data, dataset.target, test_size=0.25)



# train the model
print("[INFO] using '{}' model".format(args))
model = models[args]
model.fit(trainX, trainY)

# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(classification_report(testY, predictions,
	target_names=le.classes_))

[INFO] using 'knn' model
[INFO] evaluating...
              precision    recall  f1-score   support

       coast       0.74      0.78      0.76        77
      forest       0.84      0.82      0.83        97
     highway       0.66      0.63      0.65        63

    accuracy                           0.76       237
   macro avg       0.75      0.75      0.75       237
weighted avg       0.76      0.76      0.76       237



## Mengklasifikasikan DATA foto 3scenes dataset Menggunakan CNN

<img src="https://www.pyimagesearch.com/wp-content/uploads/2019/01/python_ml_3scenes.jpg"></img>

<img src="https://www.pyimagesearch.com/wp-content/uploads/2019/01/python_ml_cnn.png"></img>
scenes dataset and includes 948 total images of 3 scenes:

Coast (360 of images)
Forest (328 of images)
Highway (260 of images)

CNN melakukan pemrosesan langsung terhadap pixel gambar dan dapat mencari fitur dari gambar secara otomatis.


<img src="https://docs.google.com/uc?export=download&id=1vVxc0XycPBwTL3fdT92MueZkpBOzG3U9"></img>

In [ ]:
from keras.models import Sequential
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from PIL import Image
from imutils import paths
import numpy as np
import argparse
import os
from keras import backend as K
import tensorflow

print("[INFO] loading images...")
imagePaths = paths.list_images("/content/python-machine-learning/3scenes")
data = []
labels = []

[INFO] loading images...



<img src="https://docs.google.com/uc?export=download&id=19NfmNnL1y5gH-HA5-bfK48h4bFShXz1b"></img>

In [ ]:
for imagePath in imagePaths:
  image = Image.open(imagePath)
  image = np.array(image.resize((32, 32)))/255.0
  data.append(image)

  label = imagePath.split(os.path.sep)[-2]
  labels.append(label)

lb = LabelBinarizer()
labels = lb.fit_transform(labels)

(trainX, testX, trainY, testY) = train_test_split(np.array(data), np.array(labels), test_size=0.25)


<img src="https://docs.google.com/uc?export=download&id=1xr-3P-JxLJmnqz-oGCdR8-JKBQDcWgVK"></img>
This time, we’re importing convolutional layer types, max pooling operations, different activation functions, and the ability to flatten. Additionally, we’re using the Adam  optimizer rather than SGD as we did in the previous simple neural network script.



In [ ]:
model = Sequential()
model.add(Conv2D(8, (3, 3), padding="same", input_shape=(32, 32, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(16, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(32, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Flatten())
model.add(Dense(3))
model.add(Activation("softmax"))

opt = Adam(lr=1e-3, decay=1e-3/50)
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
H = model.fit(trainX, trainY, validation_data=(testX, testY), epochs=50, batch_size=32)

print("[INFO] evaluating network...")
predictions = model.predict(testX, batch_size=32)
print(classification_report(testY.argmax(axis=1), predictions.argmax(axis=1), target_names=lb.classes_))

Epoch 1/50
23/23 [==============================] - 1s 32ms/step - loss: 1.0659 - accuracy: 0.4290 - val_loss: 1.0048 - val_accuracy: 0.6624
Epoch 2/50
23/23 [==============================] - 1s 26ms/step - loss: 0.9298 - accuracy: 0.6329 - val_loss: 0.8665 - val_accuracy: 0.6540
Epoch 3/50
23/23 [==============================] - 1s 26ms/step - loss: 0.7415 - accuracy: 0.7032 - val_loss: 0.6971 - val_accuracy: 0.7300
Epoch 4/50
23/23 [==============================] - 1s 25ms/step - loss: 0.6409 - accuracy: 0.7075 - val_loss: 0.6381 - val_accuracy: 0.7975
Epoch 5/50
23/23 [==============================] - 1s 26ms/step - loss: 0.5882 - accuracy: 0.7792 - val_loss: 0.5559 - val_accuracy: 0.7848
Epoch 6/50
23/23 [==============================] - 1s 25ms/step - loss: 0.5277 - accuracy: 0.7862 - val_loss: 0.4987 - val_accuracy: 0.8608
Epoch 7/50
23/23 [==============================] - 1s 26ms/step - loss: 0.4648 - accuracy: 0.8228 - val_loss: 0.4648 - val_accuracy: 0.8776
Epoch 8/50
23